# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e666ae46d7fc432838daa786db182af1d297509293d3dabcb54b25a5a06da7986403ed8ccb9fa9521e23db93b894c0c247041261b61e1e195d011c9131f985a

test:
  secret_key_base: 347599eb2dae7a2fec046e71d4a3cf3631c8eb6ccf986bd673b9233c8550d4b429eb7f05ad6ac21fa82532ae48ac7d017dcdda491bd6510d5473e2407bb17cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
